# Generated by Django 5.2.8 on 2025-11-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='projects',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
